# Site settings
name: Adrian Ogletree
description: "Adrian Ogletree's personal website and blog"
url: "http://aogletree.github.io/"

email: adrianogletree@gmail.com
github_username:  aogletree
twitter_username: oftheadriatic
blog_url: "/blog"

avatar: yes
avatar_img_path: "https://avatars2.githubusercontent.com/u/6354212"

front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty